<a href="https://colab.research.google.com/github/danie-bit/pytorch-learnings/blob/main/1_tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [18]:
# using empty
a = torch.empty(2,3)    # gives garbage values

In [15]:
a

tensor([[1.2808e-12, 0.0000e+00, 1.2409e-12],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

In [6]:
# check type
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
# using rand
torch.rand(2,3)

tensor([[0.2598, 0.2232, 0.5467],
        [0.4321, 0.2366, 0.1872]])

In [19]:
# use of seed
torch.rand(2,3)

tensor([[0.0221, 0.9903, 0.4932],
        [0.5374, 0.1655, 0.7636]])

In [20]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [21]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [22]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [24]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
x.shape

torch.Size([2, 3])

In [26]:
torch.empty_like(x)

tensor([[3616445622929465956, 6068374192585256245, 3617298930153961009],
        [6499312394864965678, 7309453675965983778, 8315168162784306286]])

In [27]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [29]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [31]:
# find data type
x.dtype

torch.int64

In [32]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [33]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [34]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [35]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [36]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [37]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [38]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [39]:
c = torch.tensor([1, -2, 3, -4])

In [40]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [41]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [42]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [43]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [44]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [45]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [46]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [51]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [53]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([17., 25.])

In [54]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([7., 8., 6.])

In [55]:
# median
torch.median(e)

tensor(7.)

In [56]:
# max and min
torch.max(e)
torch.min(e)

tensor(5.)

In [57]:
# product
torch.prod(e)

tensor(99225.)

In [58]:
# standard deviation
torch.std(e)

tensor(1.7889)

In [59]:
# variance
torch.var(e)

tensor(3.2000)

In [60]:
# argmax
torch.argmax(e)

tensor(3)

In [61]:
# argmin
torch.argmin(e)

tensor(0)

### 4. Matrix operations

In [62]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 9, 8],
        [9, 7, 9]])
tensor([[2, 6],
        [7, 7],
        [8, 3]])


In [63]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[137, 117],
        [139, 130]])

In [64]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [65]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [68]:
i = torch.randint(size=(2,3,3), low=0, high=10, dtype=torch.float32)
i

tensor([[[3., 3., 5.],
         [0., 6., 4.],
         [0., 8., 4.]],

        [[7., 2., 3.],
         [8., 5., 6.],
         [2., 9., 5.]]])

In [74]:
torch.transpose(i, 0,1)

tensor([[[3., 3., 5.],
         [7., 2., 3.]],

        [[0., 6., 4.],
         [8., 5., 6.]],

        [[0., 8., 4.],
         [2., 9., 5.]]])

In [71]:
torch.transpose(i, 2,0)

tensor([[[3., 7.],
         [0., 8.],
         [0., 2.]],

        [[3., 2.],
         [6., 5.],
         [8., 9.]],

        [[5., 3.],
         [4., 6.],
         [4., 5.]]])

In [76]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[1., 1., 2.],
        [4., 7., 2.],
        [5., 6., 1.]])

In [77]:
# determinant
torch.det(h)

tensor(-21.)

In [78]:
# inverse
torch.inverse(h)

tensor([[ 0.2381, -0.5238,  0.5714],
        [-0.2857,  0.4286, -0.2857],
        [ 0.5238,  0.0476, -0.1429]])

### 5. Comparison operations

In [79]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[4, 5, 6],
        [9, 2, 3]])
tensor([[1, 0, 2],
        [1, 2, 7]])


In [80]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[ True,  True,  True],
        [ True, False,  True]])

### 6. Special functions

In [81]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[9., 2., 4.],
        [6., 6., 8.]])

In [82]:
# log
torch.log(k)

tensor([[2.1972, 0.6931, 1.3863],
        [1.7918, 1.7918, 2.0794]])

In [83]:
# exp
torch.exp(k)    # e^k  # e = 2.71

tensor([[8.1031e+03, 7.3891e+00, 5.4598e+01],
        [4.0343e+02, 4.0343e+02, 2.9810e+03]])

In [84]:
# sqrt
torch.sqrt(k)

tensor([[3.0000, 1.4142, 2.0000],
        [2.4495, 2.4495, 2.8284]])

In [85]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.8808, 0.9820],
        [0.9975, 0.9975, 0.9997]])

In [86]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0180, 0.0180],
        [0.0474, 0.9820, 0.9820]])

In [87]:
# relu
torch.relu(k)

tensor([[9., 2., 4.],
        [6., 6., 8.]])

## Inplace Operations

In [3]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.1155, 0.0939, 0.3286],
        [0.7210, 0.8472, 0.6610]])
tensor([[0.7071, 0.1760, 0.0351],
        [0.5194, 0.1741, 0.8721]])


In [4]:
m.add_(n)

tensor([[0.8226, 0.2699, 0.3637],
        [1.2404, 1.0213, 1.5330]])

In [5]:
m

tensor([[0.8226, 0.2699, 0.3637],
        [1.2404, 1.0213, 1.5330]])

In [6]:
n

tensor([[0.7071, 0.1760, 0.0351],
        [0.5194, 0.1741, 0.8721]])

In [8]:
torch.relu(m)

tensor([[0.8226, 0.2699, 0.3637],
        [1.2404, 1.0213, 1.5330]])

In [9]:
m.relu_()

tensor([[0.8226, 0.2699, 0.3637],
        [1.2404, 1.0213, 1.5330]])

In [10]:
m

tensor([[0.8226, 0.2699, 0.3637],
        [1.2404, 1.0213, 1.5330]])

## Copying a Tensor

In [11]:
a = torch.rand(2,3)
a

tensor([[0.5718, 0.1587, 0.8559],
        [0.5905, 0.0745, 0.6324]])

In [12]:
b = a

In [13]:
b

tensor([[0.5718, 0.1587, 0.8559],
        [0.5905, 0.0745, 0.6324]])

In [14]:
a[0][0] = 0

In [15]:
a

tensor([[0.0000, 0.1587, 0.8559],
        [0.5905, 0.0745, 0.6324]])

In [16]:
b

tensor([[0.0000, 0.1587, 0.8559],
        [0.5905, 0.0745, 0.6324]])

In [17]:
id(a)

140141181301808

In [18]:
id(b)

140141181301808

In [19]:
b = a.clone()

In [20]:
a

tensor([[0.0000, 0.1587, 0.8559],
        [0.5905, 0.0745, 0.6324]])

In [21]:
b

tensor([[0.0000, 0.1587, 0.8559],
        [0.5905, 0.0745, 0.6324]])

In [22]:
a[0][0] = 10

In [23]:
a

tensor([[10.0000,  0.1587,  0.8559],
        [ 0.5905,  0.0745,  0.6324]])

In [24]:
b

tensor([[0.0000, 0.1587, 0.8559],
        [0.5905, 0.0745, 0.6324]])

In [25]:
id(a)

140141181301808

In [26]:
id(b)

140145614872144