<a href="https://colab.research.google.com/github/danie-bit/pytorch-learnings/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(   # sequential is a container
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [2]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5763],
        [0.5743],
        [0.5725],
        [0.5729],
        [0.5725],
        [0.5725],
        [0.5725],
        [0.5749],
        [0.5737],
        [0.5725]], grad_fn=<SigmoidBackward0>)

In [8]:
print("Weights of the first linear layer:")
print(model.network[0].weight)
print("Biases of the first linear layer:")
print(model.network[0].bias)

print("\nWeights of the second linear layer:")
print(model.network[2].weight)
print("Biases of the second linear layer:")
print(model.network[2].bias)

Weights of the first linear layer:
Parameter containing:
tensor([[-0.0609, -0.1417, -0.3479,  0.3118,  0.3002],
        [ 0.2123,  0.0621, -0.1420, -0.0016,  0.1355],
        [-0.4031, -0.4309, -0.3566, -0.1727, -0.1135]], requires_grad=True)
Biases of the first linear layer:
Parameter containing:
tensor([-0.0540, -0.3332,  0.3685], requires_grad=True)

Weights of the second linear layer:
Parameter containing:
tensor([[ 0.1860, -0.2906,  0.4023]], requires_grad=True)
Biases of the second linear layer:
Parameter containing:
tensor([0.2920], requires_grad=True)


In [5]:
!pip install torchinfo

In [9]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00